### PR TITLE
Get the managers' threshold from Unvault Descriptor

### PR DESCRIPTION
**Pull request by darosior**
Alternative to #97 .

Closes #97.

### CODE REVIEW

**Comment by darosior** [comment]
ACK 572be6d FWIW

**Comment by danielabrozzoni** [comment]
ACK f3b19f324def9009833740e86f9c4aef1717fa53

**Review by danielabrozzoni — APPROVED** [review]

**Comment by darosior** [comment]
Arg i should have documented when it returns None..

**Comment by darosior** [comment]
Well merging, will open an issue

**Pull request merged**
